# Generated by Django 4.2.2 on 2023-06-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0005_company_created_at_company_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.CharField(max_length=128, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="mobile",
            field=models.CharField(verbose_name="Mobile"),
        ),
    ]
