# Generated by Django 4.2.2 on 2023-07-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0008_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="employee.department"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="employee.position"),
        ),
    ]
