# Generated by Django 4.2.2 on 2023-07-04 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0009_alter_employee_department_alter_employee_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("longitude", models.CharField(max_length=255)),
                ("latitude", models.CharField(max_length=255)),
                ("status", models.CharField(choices=[("current", "Current"), ("expired", "Expired")], max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="employee.companybranch",
                    ),
                ),
            ],
        ),
    ]
