# Generated by Django 4.2.2 on 2023-07-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0010_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.FloatField(),
        ),
    ]
