from .employee_create_view import EmployeeCreateView
from .employee_update_view import EmployeeUpdateView
from .employee_list_view import EmployeeListView
from .employee_detail_view import EmployeeDetailView
from .employee_delete_view import EmployeeDeleteView