# Generated by Django 4.2.2 on 2023-07-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("check_in", models.DateTimeField()),
                ("check_out", models.DateTimeField()),
                ("worked_hours", models.FloatField()),
                ("default_check_in", models.FloatField()),
                ("default_check_out", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
