# Generated by Django 4.2.2 on 2023-07-05 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("check_in", models.DateTimeField()),
                ("check_out", models.DateTimeField(null=True)),
                ("worked_hours", models.FloatField(null=True)),
                ("default_check_in", models.FloatField(null=True)),
                ("default_check_out", models.FloatField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("branch", models.CharField(max_length=255)),
                ("check_in", models.DateTimeField()),
                ("check_out", models.DateTimeField(null=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_details",
                        to="attendance.attendance",
                    ),
                ),
            ],
        ),
    ]
