# Generated by Django 4.2.2 on 2023-07-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("branch", models.CharField(max_length=255)),
                ("check_in", models.DateTimeField()),
                ("check_out", models.DateTimeField()),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_details",
                        to="attendance.attendance",
                    ),
                ),
            ],
        ),
    ]
