# Generated by Django 4.2.2 on 2023-07-05 06:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_attendancedetail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancedetail",
            name="attendance",
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
        migrations.DeleteModel(
            name="AttendanceDetail",
        ),
    ]
