# Generated by Django 4.2.2 on 2023-07-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="check_out",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="worked_hours",
            field=models.FloatField(null=True),
        ),
    ]
