# Generated by Django 4.2.2 on 2023-07-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0005_alter_attendance_check_out_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="default_check_in",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="default_check_out",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="attendancedetail",
            name="check_out",
            field=models.DateTimeField(null=True),
        ),
    ]
