# Generated by Django 4.2.2 on 2023-07-05 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0006_alter_attendance_default_check_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancedetail",
            name="attendance",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_details",
                to="attendance.attendance",
            ),
        ),
    ]
